/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.POO.Presentation.Desktop;

import br.edu.ifnmg.POO.DomainModel.Aluno;
import br.edu.ifnmg.POO.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.POO.DomainModel.Professor;
import br.edu.ifnmg.POO.DomainModel.Turma;
import br.edu.ifnmg.POO.Persistence.ProfessorRepositorio;
import br.edu.ifnmg.POO.Persistence.TurmaRepositorio;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author petronio
 */
public class TurmaBuscar extends javax.swing.JInternalFrame {

    ProfessorRepositorio repo_professor;
    TurmaRepositorio repositorio;
    
    Turma filtro;
    
    /**
     * Creates new form TurmaBuscar
     */
    public TurmaBuscar() {
        repo_professor = new ProfessorRepositorio();
        repositorio = new TurmaRepositorio();
        
        initComponents();
        
        List<String> semestres = repositorio.listartSemestres();
        
        ComboBoxModel<String> model_semestres 
                = new DefaultComboBoxModel<>(new Vector(semestres));
        
        cbxSemestres.setModel(model_semestres);
        
        
        List<Professor> professores = repo_professor.Buscar(null);
        
        ComboBoxModel<Professor> model_professores 
                = new DefaultComboBoxModel<>(new Vector(professores));
        
        cbxProfessores.setModel(model_professores);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxSemestres = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxProfessores = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxResultado = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listagem de Turmas");

        jLabel1.setText("Semestre:");

        jLabel2.setText("Professores:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNovo.setText("Nova");

        tbxResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbxResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbxResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(28, 28, 28)
                                .addComponent(btnNovo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(cbxSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxProfessores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            filtro = new Turma();
            
            filtro.setSemestre( (String) cbxSemestres.getSelectedItem() );
            filtro.setProfessor((Professor) cbxProfessores.getSelectedItem() );
            
            List<Turma> turmas = repositorio.Buscar(filtro);
            
            preencherTabela(turmas);
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(TurmaBuscar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbxResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxResultadoMouseClicked
        
        int linha = this.tbxResultado.getSelectedRow();
        
        int id = Integer.parseInt( this.tbxResultado.getValueAt(linha, 0).toString() );
        
        Turma turma = repositorio.Abrir(id);
        
        TurmaEditar tela = new TurmaEditar(turma, repositorio);
        
        this.getParent().add(tela);
        
        tela.show();
    }//GEN-LAST:event_tbxResultadoMouseClicked

    public void preencherTabela(List<Turma> lista){
       
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Semestre");
        modelo.addColumn("Professor");
        
        for(Turma a : lista){
            Vector linha = new Vector();
            linha.add(a.getId());
            linha.add(a.getSemestre());
            linha.add(a.getProfessor().getNome());
            
            modelo.addRow(linha);
        }
       
        tbxResultado.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<Professor> cbxProfessores;
    private javax.swing.JComboBox<String> cbxSemestres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbxResultado;
    // End of variables declaration//GEN-END:variables
}
